### ISSUE TITLE
[Google] Login persistence and custom provider parameters

### ISSUE THREAD

**Issue by edgargaza** [askidmobile/angular-6-social-login-v2#1]
Hello everyone. I would like to know if there's some way to set different session persistance.

And also, there's any way to be able to set my own provider options? Like "prompt" to "select_account" and others.

Thanks in advance!

**Comment by edgargaza** [comment]
**[Pull request done](https://github.com/askidmobile/angular-6-social-login-v2/pull/2)** to add custom Google provider parameters support.

**Comment by askidmobile** [comment]
Hello. Now I'm working on an improved vk (vk.com) authorization, just like you want, and then I'll add special options for BaseProvider to set additional parameters. Thanks again for your feedback.

**Comment by edgargaza** [comment]
Oh perfect! Anyway, there you have the code. When you finish the project, you will push it here or in some other repo?

**Comment by edgargaza** [comment]
Oh perfect then! ;)

**Comment by askidmobile** [comment]
One question, for what you need add get user() function,
and import { MAT_CHIPS_DEFAULT_OPTIONS } from '@angular/material'; - for use material chips you must use the code in your app.

And last, how do you use this modification like this

        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider({client_id: "Your-Google-Client-Id", scope: 'email'})
        },

I think to add some params like this:

        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider("Your-Google-Client-Id"),
          options: [{ scope: "email", more*: "more*" }]
        },

This will be necessary to ensure compatibility versions.

**Comment by edgargaza** [comment]
Woops, that's right. The mat chips import is useless, I'm sorry.

I did the user getter to be able to access some user info, like it's email, name, etc. And yea, that's a good idea to keep the options separated from the provider ID.
